local file = assert(io.open(arg[1], "r"))
local source = file:read("*a")
file:close()
local block = assert(source:match("(local function log_level.-)\nfunction action_logs_json"))
local compile = loadstring or load
local parse = assert(compile(block .. "\nreturn append_log_entries"))()
local entries = {}
parse(entries, "system", 'Thu Sep 10 13:25:36 2026 daemon.err candy[42]: \27[2m2026-09-10T05:25:36.123Z\27[0m \27[33m WARN\27[0m candy_core: event="node_connect_failed" error="authentication rejected"', true)
assert(#entries == 1)
assert(entries[1].level == "warn", entries[1].level)
assert(entries[1].event == "node_connect_failed", entries[1].event)
assert(entries[1].timestamp == "2026-09-10T05:25:36Z", entries[1].timestamp)
assert(not entries[1].detail:find("\27", 1, true))
parse(entries, "system", 'Thu Sep 10 13:25:37 2026 daemon.err candy[42]: level=info event=retry result=recorded error_code=none', true)
assert(entries[2].level == "info")
assert(entries[2].timestamp == os.date("!%Y-%m-%dT%H:%M:%SZ", os.time({year=2026, month=9, day=10, hour=13, min=25, sec=37})))
parse(entries, "system", 'Thu Sep 10 13:25:38 2026 daemon.err dropbear[1]: unrelated', true)
assert(#entries == 2)
print("OpenWrt log diagnostics tests passed")
