[package]
name = "client-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
candy-core = { path = "../../crates/candy-core" }
carrier-client = { path = "../../crates/carrier-client" }
candy-proto = { path = "../../crates/candy-proto" }
carrier-runtime = { path = "../../crates/carrier-runtime" }
carrier-transport = { path = "../../crates/carrier-transport" }
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
nix.workspace = true
rustls.workspace = true
serde_json.workspace = true
serde.workspace = true
sha2.workspace = true
toml.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
